[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.13.0, <3.14"
dependencies = [
    "niquests>=3.15.2",
    "robyn>=0.72.2",
    "tldextract>=5.3.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
